# This is a basic workflow to help you get started with Actions

name: Build and deploy JS files

on:
  push:
    branches: ["master"]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Update APT
        id: update-apt
        run: sudo apt-get update

      - name: Install Node.JS and NPM
        id: install-packages
        run: sudo apt-get install nodejs npm

      # Runs a set of commands using the runners shell
      # - /
      # - /build/ - JS blobs
      # - /data/ - Library data
      - name: Create artifact root
        id: create-root
        run: |
          mkdir artifactRoot
          mkdir artifactRoot/build
          mkdir artifactRoot/data

      - name: Copy static files
        id: copy-static
        run: |
          cp index.html artifactRoot/
          cp style.css artifactRoot/
          cp favicon.png artifactRoot/

      - name: Install NPM dependencies
        id: install-npm
        run: npm install

      - name: Compile JS files
        id: compile-js
        run: npm start

      - name: Copy JS blobs
        id: copy-blobs
        run: |
          cp build/index.js artifactRoot/build/
          cp build/audio-processor.mjs artifactRoot/build/

      - name: Copy sourcemaps
        id: copy-sourcemaps
        run: |
          cp build/index.js.map artifactRoot/build/
          cp build/audio-processor.mjs.map artifactRoot/build/

      - name: Copy library
        id: copy-library
        run: |
          cp -rv data/library/ artifactRoot/data/
          cp -rv data/songs/ artifactRoot/data/

      - name: Create artifact
        id: create-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: artifactRoot/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.create-artifact.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy page for all to see
        id: deployment
        uses: actions/deploy-pages@v4
